import 'package:flutter/material.dart';

import '../path_to_my_banner_ad_widget.dart';

void main() {
  runApp(capitals_currency());
}

class capitals_currency extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Capitals & Currency',
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueAccent,
          iconTheme: IconThemeData(
            color: Colors.black,
          ),
          leading: IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
          title: Text('Capitals & Currency'),
        ),

        body: ListView( // Wrap the Column with a ListView
            children: [
            MyBannerAdWidget(), // Add the banner ad here SingleChildScrollView(
          DataTable(
            dataRowHeight: 80.0, // Adjust this value as needed
            decoration: BoxDecoration(color: Colors.white70),border: TableBorder.all(color: Colors.green),
            columns: [
              DataColumn(label: Text('Country')),
              DataColumn(label: Text('Capital')),
              DataColumn(label: Text('Currency')),
            ],
            rows: [
              for (var i = 0; i < data.length; i++)
                DataRow(
                  cells: [
                    DataCell(Text(data[i][0])),
                    DataCell(Text(data[i][1])),
                    DataCell(Text(data[i][2])),
                  ],
                ),
            ],
          ),
        ]),
      ),
    );
  }
}

final List<List<String>> data = [


['Afghanistan', 'Kabul', 'Afghan Afghani'],
['Albania', 'Tirana', 'Albanian Lek'],
['Algeria', 'Algiers', 'Algerian Dinar'],
['Andorra', 'Andorra la Vella', 'Euro'],
['Angola', 'Luanda', 'Angolan Kwanza'],
['Antigua and Barbuda', "Saint John's", 'East Caribbean Dollar'],
['Argentina', 'Buenos Aires', 'Argentine Peso'],
['Armenia', 'Yerevan', 'Armenian Dram'],
['Australia', 'Canberra', 'Australian Dollar'],
['Austria', 'Vienna', 'Euro'],
['Azerbaijan', 'Baku', 'Azerbaijani Manat'],
['Bahamas', 'Nassau', 'Bahamian Dollar'],
['Bahrain', 'Manama', 'Bahraini Dinar'],
['Bangladesh', 'Dhaka', 'Bangladeshi Taka'],
['Barbados', 'Bridgetown', 'Barbadian Dollar'],
['Belarus', 'Minsk', 'Belarusian Ruble'],
['Belgium', 'Brussels', 'Euro'],
['Belize', 'Belmopan', 'Belize Dollar'],
['Benin', 'Porto-Novo', 'West African CFA franc'],
['Bhutan', 'Thimphu', 'Bhutanese Ngultrum'],
['Bolivia', 'Sucre', 'Bolivian Boliviano'],
['Bosnia and Herzegovina', 'Sarajevo', 'Bosnia and Herzegovina Convertible Mark'],
['Botswana', 'Gaborone', 'Botswana Pula'],
['Brazil', 'Brasília', 'Brazilian Real'],
['Brunei', 'Bandar Seri Begawan', 'Brunei Dollar'],
['Bulgaria', 'Sofia', 'Bulgarian Lev'],
['Burkina Faso', 'Ouagadougou', 'West African CFA franc'],
['Burundi', 'Bujumbura', 'Burundian Franc'],
['Cabo Verde', 'Praia', 'Cape Verdean Escudo'],
['Cambodia', 'Phnom Penh', 'Cambodian Riel'],
['Cameroon', 'Yaoundé', 'Central African CFA franc'],
['Canada', 'Ottawa', 'Canadian Dollar'],
['Central African Republic', 'Bangui', 'Central African CFA franc'],
['Chad', 'N Djamena', 'Central African CFA franc'],
['Chile', 'Santiago', 'Chilean Peso'],
['China', 'Beijing', 'Chinese Yuan'],
['Colombia', 'Bogotá', 'Colombian Peso'],
['Comoros', 'Moroni', 'Comorian Franc'],
['Congo (Congo-Brazzaville)', 'Brazzaville', 'Central African CFA franc'],
['Costa Rica', 'San José', 'Costa Rican Colón'],
['Croatia', 'Zagreb', 'Croatian Kuna'],
['Cuba', 'Havana', 'Cuban Peso'],
['Cyprus', 'Nicosia', 'Euro'],
['Czechia (Czech Republic)', 'Prague', 'Czech Koruna'],
['Denmark', 'Copenhagen', 'Danish Krone'],
['Djibouti', 'Djibouti', 'Djiboutian Franc'],
['Dominica', 'Roseau', 'East Caribbean Dollar'],
['Dominican Republic', 'Santo Domingo', 'Dominican Peso'],
['Ecuador', 'Quito', 'United States Dollar'],
['Egypt', 'Cairo', 'Egyptian Pound'],
['El Salvador', 'San Salvador', 'United States Dollar'],
['Equatorial Guinea', 'Malabo', 'Central African CFA franc'],
['Eritrea', 'Asmara', 'Eritrean Nakfa'],
['Estonia', 'Tallinn', 'Euro'],
['Eswatini (fmr. "Swaziland")', 'Mbabane', 'Swazi Lilangeni'],
['Ethiopia', 'Addis Ababa', 'Ethiopian Birr'],
['Fiji', 'Suva', 'Fijian Dollar'],
['Finland', 'Helsinki', 'Euro'],
['France', 'Paris', 'Euro'],
['Gabon', 'Libreville', 'Central African CFA franc'],
['Gambia', 'Banjul', 'Gambian Dalasi'],
['Georgia', 'Tbilisi', 'Georgian Lari'],
['Germany', 'Berlin', 'Euro'],
['Ghana', 'Accra', 'Ghanaian Cedi'],
['Greece', 'Athens', 'Euro'],
['Grenada', "St. George's", 'East Caribbean Dollar'],
['Guatemala', 'Guatemala City', 'Guatemalan Quetzal'],
['Guinea', 'Conakry', 'Guinean Franc'],
['Guinea-Bissau', 'Bissau', 'West African CFA franc'],
['Guyana', 'Georgetown', 'Guyanese Dollar'],
['Haiti', 'Port-au-Prince', 'Haitian Gourde'],
['Holy See', 'Vatican City', 'Euro'],
['Honduras', 'Tegucigalpa', 'Honduran Lempira'],
['Hungary', 'Budapest', 'Hungarian Forint'],
['Iceland', 'Reykjavik', 'Icelandic Króna'],
['India', 'New Delhi', 'Indian Rupee'],
['Indonesia', 'Jakarta', 'Indonesian Rupiah'],
['Iran', 'Tehran', 'Iranian Rial'],
['Iraq', 'Baghdad', 'Iraqi Dinar'],
['Ireland', 'Dublin', 'Euro'],
['Israel', 'Jerusalem', 'Israeli New Shekel'],
['Italy', 'Rome', 'Euro'],
['Jamaica', 'Kingston', 'Jamaican Dollar'],
['Japan', 'Tokyo', 'Japanese Yen'],
['Jordan', 'Amman', 'Jordanian Dinar'],
['Kazakhstan', 'Nur-Sultan', 'Kazakhstani Tenge'],
['Kenya', 'Nairobi', 'Kenyan Shilling'],
['Kiribati', 'South Tarawa', 'Kiribati Dollar'],
['Kuwait', 'Kuwait City', 'Kuwaiti Dinar'],
['Kyrgyzstan', 'Bishkek', 'Kyrgyzstani Som'],
['Laos', 'Vientiane', 'Lao Kip'],
['Latvia', 'Riga', 'Euro'],
['Lebanon', 'Beirut', 'Lebanese Pound'],
['Lesotho', 'Maseru', 'Lesotho Loti'],
['Liberia', 'Monrovia', 'Liberian Dollar'],
['Libya', 'Tripoli', 'Libyan Dinar'],
['Liechtenstein', 'Vaduz', 'Swiss Franc'],
['Lithuania', 'Vilnius', 'Euro'],
['Luxembourg', 'Luxembourg City', 'Euro'],
['Madagascar', 'Antananarivo', 'Malagasy Ariary'],
['Malawi', 'Lilongwe', 'Malawian Kwacha'],
['Malaysia', 'Kuala Lumpur', 'Malaysian Ringgit'],
['Maldives', 'Malé', 'Maldivian Rufiyaa'],
['Mali', 'Bamako', 'West African CFA franc'],
['Malta', 'Valletta', 'Euro'],
['Marshall Islands', 'Majuro', 'United States Dollar'],
['Mauritania', 'Nouakchott', 'Mauritanian Ouguiya'],
['Mauritius', 'Port Louis', 'Mauritian Rupee'],
['Mexico', 'Mexico City', 'Mexican Peso'],
['Micronesia', 'Palikir', 'United States Dollar'],
['Moldova', 'Chisinau', 'Moldovan Leu'],
['Monaco', 'Monaco', 'Euro'],
['Mongolia', 'Ulaanbaatar', 'Mongolian Tugrik'],
['Montenegro', 'Podgorica', 'Euro'],
['Morocco', 'Rabat', 'Moroccan Dirham'],
['Mozambique', 'Maputo', 'Mozambican Metical'],
['Myanmar (formerly Burma)', 'Naypyidaw', 'Burmese Kyat'],
['Namibia', 'Windhoek', 'Namibian Dollar'],
['Nauru', 'Yaren', 'Australian Dollar'],
['Nepal', 'Kathmandu', 'Nepalese Rupee'],
['Netherlands', 'Amsterdam', 'Euro'],
['New Zealand', 'Wellington', 'New Zealand Dollar'],
['Nicaragua', 'Managua', 'Nicaraguan Córdoba'],
['Niger', 'Niamey', 'West African CFA franc'],
['Nigeria', 'Abuja', 'Nigerian Naira'],
['North Korea', 'Pyongyang', 'North Korean Won'],
['North Macedonia (formerly Macedonia)', 'Skopje', 'Macedonian Denar'],
['Norway', 'Oslo', 'Norwegian Krone'],
['Oman', 'Muscat', 'Omani Rial'],
['Pakistan', 'Islamabad', 'Pakistani Rupee'],
['Palau', 'Ngerulmud', 'United States Dollar'],
['Palestine State', 'East Jerusalem', 'Israeli New Shekel'],
['Panama', 'Panama City', 'Panamanian Balboa'],
['Papua New Guinea', 'Port Moresby', 'Papua New Guinean Kina'],
['Paraguay', 'Asunción', 'Paraguayan Guarani'],
['Peru', 'Lima', 'Peruvian Sol'],
['Philippines', 'Manila', 'Philippine Peso'],
['Poland', 'Warsaw', 'Polish Złoty'],
['Portugal', 'Lisbon', 'Euro'],
['Qatar', 'Doha', 'Qatari Rial'],
['Romania', 'Bucharest', 'Romanian Leu'],
['Russia', 'Moscow', 'Russian Ruble'],
['Rwanda', 'Kigali', 'Rwandan Franc'],
['Saint Kitts and Nevis', 'Basseterre', 'East Caribbean Dollar'],
['Saint Lucia', 'Castries', 'East Caribbean Dollar'],
['Saint Vincent and the Grenadines', 'Kingstown', 'East Caribbean Dollar'],
['Samoa', 'Apia', 'Samoan Tala'],
['San Marino', 'San Marino', 'Euro'],
['Sao Tome and Principe', 'São Tomé', 'São Tomé and Príncipe Dobra'],
['Saudi Arabia', 'Riyadh', 'Saudi Riyal'],
['Senegal', 'Dakar', 'West African CFA franc'],
['Serbia', 'Belgrade', 'Serbian Dinar'],
['Seychelles', 'Victoria', 'Seychellois Rupee'],
['Sierra Leone', 'Freetown', 'Sierra Leonean Leone'],
['Singapore', 'Singapore', 'Singapore Dollar'],
['Slovakia', 'Bratislava', 'Euro'],
['Slovenia', 'Ljubljana', 'Euro'],
['Solomon Islands', 'Honiara', 'Solomon Islands Dollar'],
['Somalia', 'Mogadishu', 'Somali Shilling'],
['South Africa', 'Pretoria', 'South African Rand'],
['South Korea', 'Seoul', 'South Korean Won'],
['South Sudan', 'Juba', 'South Sudanese Pound'],
['Spain', 'Madrid', 'Euro'],
['Sri Lanka', 'Colombo', 'Sri Lankan Rupee'],
['Sudan', 'Khartoum', 'Sudanese Pound'],
['Suriname', 'Paramaribo', 'Surinamese Dollar'],
['Sweden', 'Stockholm', 'Swedish Krona'],
['Switzerland', 'Bern', 'Swiss Franc'],
['Syria', 'Damascus', 'Syrian Pound'],
['Tajikistan', 'Dushanbe', 'Tajikistani Somoni'],
['Tanzania', 'Dodoma', 'Tanzanian Shilling'],
['Thailand', 'Bangkok', 'Thai Baht'],
['Timor-Leste', 'Dili', 'United States Dollar'],




];
