import 'package:flutter/material.dart';

import '../path_to_my_banner_ad_widget.dart';

void main() {
  runApp(important_dates());
}

class important_dates extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Important Dates',
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueAccent,
          iconTheme: IconThemeData(
            color: Colors.black,
          ),
          leading: IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
          title: Text("Important Dates"),
        ),

        body: ListView( // Wrap the Column with a ListView
            children: [
              MyBannerAdWidget(), // Add the banner ad here SingleChildScrollView(
              DataTable(
                dataRowHeight: 80.0,
                decoration: BoxDecoration(color: Colors.white70),border: TableBorder.all(color: Colors.black87),
                columns: [
                  DataColumn(label: Text('Date')),
                  DataColumn(label: Text("Speciality")),
                ],
                rows: [
                  for (var i = 0; i < data.length; i++)
                    DataRow(
                      cells: [
                        DataCell(Text(data[i][0])),
                        DataCell(Text(data[i][1])),
                      ],
                    ),
                ],
              ),
            ]),
      ),
    );
  }
}

final List<List<String>> data = [

  ['1st January', 'English New Year, Army Medical Corps Establishment Day, Global Family Day, World Peace Day'],
  ['4th January', 'World Braille Day'],
  ['6th January', 'World War Orphans Day'],
  ['9th January', 'Pravasi Bharatiya Divas NRI Day'],
  ['10th January', 'World Laughter Day, World Hindi Day'],
  ['11th January', 'Death anniversary of Lal Bahadur Shastri'],
  ['12th January', 'National Youth Day (Birth Day of Swami Vivekanand)'],
  ['15th January', 'Army Day (Field Marshall K.M. Cariappa took over the command of Army on this day in 1949 from the British), Pongal, Makar Sankranti'],
  ['25th January', 'International Customs Duty Day, India Tourism Day, National Voters Day'],
  ['26th January', 'Republic Day'],
  ['27th January', 'International Holocaust Day (The largest Nazi death camp, Auschwitz-Birkenau was liberated by Soviet troops on Jan 27, 1945.), International Day of Commemoration'],
  ['28th January', 'Birth Anniversary of Lala Lajpat Rai'],
  ['30th January', 'Mahatma Gandhi’s Martyrdom Day (Martyr’s day), World Leprosy Eradication Day'],
  ['1st February', 'Indian Coast Guard Day'],
  ['2nd February', 'World Wetlands Day'],
  ['4th February', 'World Cancer Day, National Day of Sri Lanka'],
  ['7th February', 'International Development Week'],
  ['12th February', 'Darwin Day, Abraham Lincoln’s Birthday'],
  ['13th February', 'Sarojini Naidu’s Birth Anniversary'],
  ['14th February', 'Saint Valentine’s Day'],
  ['18th February', 'Taj Mahotsav'],
  ['20th February', 'World Day of Social Justice'],
  ['21st February', 'International Mother Language Day'],
  ['22nd February', 'World Scout Day'],
  ['24th February', 'Central Excise Day'],
  ['27th February', 'World Sustainable Energy Day'],
  ['28th February', 'National Science Day'],
  ['1st March', 'Zero Discrimination Day, World Civil Defence Day'],
  ['3rd March', 'World Wildlife Day, World Hearing Day'],
  ['4th March', 'National Safety Day'],
  ['8th March', 'International Women’s Day'],
  ['10th March', 'CISF Raising Day'],
  ['13th March', 'No Smoking Day (Second Wednesday of March)'],
  ['14th March', 'Pi Day, International Day of Action for Rivers'],
  ['15th March', 'World Consumer Rights Day'],
  ['16th March', 'National Vaccination Day'],
  ['18th March', 'Ordnance Factories Day (India)'],
  ['20th March', 'International Day of Happiness, World Sparrow Day'],
  ['21st March', 'World Forestry Day, World Down syndrome Day, World Poetry Day'],
  ['22nd March', 'World Water Day'],
  ['23rd March', 'World Meteorological Day'],
  ['24th March', 'World Tuberculosis (TB) Day'],
  ['27th March', 'World Theatre Day'],
  ['1st April', 'Orissa Day, Prevention of Blindness week'],
  ['2nd April', 'World Autism Awareness Day'],
  ['4th April', 'International Day for Mine Awareness'],
  ['5th April', 'National Maritime Day'],
  ['7th April', 'World Health Day'],
  ['10th April', 'World Homeopathy Day'],
  ['11th April', 'National Safe Motherhood Day, National Pet Day'],
  ['13th April', 'Jallianwallah Bagh Massacre Day (1919)'],
  ['17th April', 'World Haemophilia Day'],
  ['18th April', 'World Heritage Day'],
  ['19th April', 'World Liver Day'],
  ['21st April', 'National Civil Service Day, Secretaries’ Day'],
  ['22nd April', 'World Earth Day'],
  ['23rd April', 'World Book and Copyright Day'],
  ['24th April', 'National Panchayati Day'],
  ['25th April', 'World Malaria Day, World Veterinary Day'],
  ['26th April', 'World Intellectual Property Day'],
  ['27th April', 'World Veterinary Day'],
  ['28th April', 'World Day for Safety and Health at Work'],
  ['29th April', 'International Dance Day'],
  ['30th April', 'Ayushman Bharat Diwas'],
  ['1st May', 'International Labour Day'],
  ['1st May (1st Sunday)', 'World Laughter Day'],
  ['3rd May', 'Press Freedom Day'],
  ['3rd May (1st Tuesday)', 'World Asthma Day'],
  ['4th May', 'Coal miner’s day'],
  ['8th May', 'World Red Cross Day'],
  ['8th May (2nd Sunday)', 'Mother’s Day'],
  ['9th May', 'Victory day'],
  ['2nd Sunday of May', 'Mother’s Day [10th May]'],
  ['11th May', 'National Technology Day'],
  ['12th May', 'International Nurses day'],
  ['14th May', 'World Migratory day'],
  ['15th May', 'International Day of the Family'],
  ['17th May', 'World Telecommunication Day (Information Society Day)'],
  ['21st May', 'Anti-terrorism day'],
  ['24th May', 'Commonwealth Day'],
  ['31st May', 'Anti-Tobacco Day'],
  ['4th June', 'International Day of Innocent Children Victims of Aggression'],
  ['5th June', 'World Environment Day'],
  ['7th June', 'International level crossing awareness day'],
  ['8th June', 'World ocean day'],
  ['12th June', 'World day against Child Labour'],
  ['14th June', 'World blood donor day'],
  ['17th June', 'World day to combat desertification and drought'],
  ['20th June', 'World Refugee day'],
  ['21st June (3rd Sunday)', 'Father’s Day'],
  ['21st June', 'World Music Day, International Yoga Day'],
  ['23rd June', 'United Nation’s public service day'],
  ['23rd June', 'International Widow’s day'],
  ['26th June', 'International Day against Drug abuse & Illicit Trafficking'],
  ['1st July', 'National Doctor’s day'],
  ['6th July', 'World Zoonoses Day'],
  ['11th July', 'World Population Day'],
  ['12th July', 'World Malala day'],
  ['18th July', 'Nelson Mandela International Day'],
  ['28th July', 'World Nature conservation day, World Hepatitis Day'],
  ['7th August (1st Sunday)', 'International Friendship Day'],
  ['3rd August', 'Independence day of Niger'],
  ['5th August', 'Independence day of upper Volta'],
  ['6th August', 'Hiroshima Day'],
  ['9th August', 'International day of World’s indigenous people'],
  ['9th August', 'Quit India movement Day and Nagasaki Day'],
  ['12th August', 'International Youth day'],
  ['15th August', 'Independence Day of India'],
  ['23rd August', 'International Day for the remembrance of the slave trade and its abolition'],
  ['29th August', 'National Sports Day'],
  ['5th September', 'Teachers’ Day (Dr Radhakrishnan’s birthday), Forgiveness day'],
  ['8th September', 'World Literacy Day'],
  ['14th September', 'Hindi day, World First Air Day'],
  ['15th September', 'Engineer’s day in India, International Day of Democracy'],
  ['16th September', 'World Ozone Day, International Day for Preservation'],
  ['21st September', 'Alzheimer’s Day, International day of peace'],
  ['25th September', 'Social justice day'],
  ['26th September', 'Day of the Deaf'],
  ['27th September', 'World Tourism Day'],
  ['29th September', 'World Heart Day'],
  ['30th September', 'International Translation Day'],
  ['25th September (fourth Sunday of September)', 'World Rivers Day'],
  ['1st October', 'International Day of the Older person'],
  ['2nd October', 'Mahatma Gandhi’s birthday, the International day of non-violence'],
  ['3rd October (first Monday)', 'World Habitat Day'],
  ['4th October', 'World Animal Welfare Day'],
  ['5th October', 'World Teacher’s day'],
  ['8th October', 'Indian Air Force Day'],
  ['9th October', 'World Post Office day'],
  ['10th October', 'National Post Day'],
  ['11th October', 'International girl child day'],
  ['12th October', 'World Arthritis day'],
  ['13th October', 'UN International Day for National disaster reduction'],
  ['13th October (2nd Thursday)', 'World Sight Day'],
  ['14th October', 'World Standards Day'],
  ['15th October', 'World White Cane Day (guiding the Blind)'],
  ['16th October', 'World Food Day'],
  ['17th October', 'International Day for the eradication of poverty'],
  ['20th October', 'World statistics day'],
  ['24th October', 'UN Day, World development information Day'],
  ['30th October', 'World Thrift Day'],
  ['31st October', 'National Unity Day'],
  ['1st November', 'World vegan day'],
  ['5th November', 'World Radiography Day, World tsunami day'],
  ['7th November', 'National Cancer Awareness Day'],
  ['9th November', 'Legal Services day'],
  ['14th November', 'Children’s Day in India, Jawaharlal Nehru’s birthday'],
  ['16th November', 'International day for Endurance'],
  ['17th November', 'World Student Day, National Journalism day, National Epilepsy Day'],
  ['18th November', 'World Adult day'],
  ['19th November', 'World Citizen day'],
  ['20th November', 'Africa Industrialization Day, Universal children’s day'],
  ['21st November', 'World Television Day, World Fisheries day'],
  ['25th November', 'World Non-veg day'],
  ['26th November', 'Law day'],
  ['29th November', 'International Day of Solidarity with Palestinian People'],
  ['30th November', 'Flag day'],
  ['1st December', 'World Aids Day'],
  ['2nd December', 'World Computer literacy day, International day of abolition of slavery'],
  ['3rd December', 'International Day of People with disabilities, World conservation day'],
  ['4th December', 'Navy Day'],
  ['5th December', 'International volunteer day for economic and social development'],
  ['7th December', 'Armed Forces Flag Day, International civil aviation day'],
  ['9th December', 'The International day against corruption'],
  ['10th December', 'Human Right Day'],
  ['11th December', 'International Mountain day'],
  ['14th December', 'International Energy day'],
  ['16th December', 'Vijay Diwas'],
  ['18th December', 'International Migrants day'],
  ['19th December', 'Goa’s liberation day'],
  ['20th December', 'International Human solidarity'],
  ['22nd December', 'National Mathematics Day'],
  ['23rd December', 'Kisan Divas (Farmer’s Day)'],
  ['24th December', 'National Consumers Day']


];
